import '../styles/globalslight.css'
export const metadata = {
    title: 'Abstract Blow Game',
    description: 'Generated by create next app',
}



export default function RootLayout({children}) {
    {
        return (
            <html lang="fr">
            <body>{children}</body>
            </html>
        )
    }
}